# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_remove_kirrurl_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='short', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
